import { GROUPS } from '../domain/model.js';
import { reservationsPanel } from './reservations.js';
import { escapeHtml as e, icon, empty } from './helpers.js';
export function otherPage(state, ui, storageKind) {
  return `<div class="page-heading"><div><p class="eyebrow">WORKSPACE TOOLS</p><h1>その他</h1><p class="page-description">送信の準備、メンバー管理、データの保管。</p></div></div><div id="alerts"></div><nav class="section-jumps" aria-label="その他の項目"><a href="#reservation-section" data-scroll="reservation-section">Teams送信予約</a><a href="#member-section" data-scroll="member-section">メンバー管理</a><a href="#settings-section" data-scroll="settings-section">設定</a><a href="#backup-section" data-scroll="backup-section">バックアップ・復元</a></nav>${reservationsPanel(state, ui.reservationFilter)}<section class="settings-card" id="member-section"><div class="panel-heading"><div><h2>${icon('people')} メンバー管理</h2><p class="field-hint">名前と日付ごとの予定を登録できます。</p></div><button class="button small" data-new-member>${icon('plus')}メンバーを追加</button></div>${Object.entries(GROUPS).map(([key, { label, limit }]) => {
    const members = state.members.filter(m => m.group === key);
    return `<div class="member-management-group"><div class="group-label"><h3>${label}</h3><span>${members.length} / ${limit}名</span></div>${members.length ? `<div class="member-management-list">${members.map(m => `<div class="member-management-row"><span>${e(m.name)}</span><button class="text-button" data-edit-member="${e(m.id)}">編集</button><button class="text-button danger-text" data-delete-member="${e(m.id)}" aria-label="${e(m.name)}を削除">削除</button></div>`).join('')}</div>` : '<p class="muted small-note">未登録</p>'}</div>`;
  }).join('')}</section><div class="other-grid"><section class="settings-card" id="settings-section"><div class="panel-heading"><h2>${icon('settings')} 設定</h2></div><form id="settings-form"><label class="setting-row"><span>期限時刻の初期値<small>新規登録時に使用</small></span><input name="defaultDueTime" type="time" required value="${e(state.settings.defaultDueTime)}"></label><label class="setting-row"><span>アプリ内アラーム<small>アプリを開いたときに確認</small></span><input type="checkbox" name="alarmsEnabled" ${state.settings.alarmsEnabled ? 'checked' : ''} aria-label="アプリ内アラームを有効にする"></label><label class="setting-row"><span>カレンダーは月曜始まり</span><input name="weekStartsMonday" type="checkbox" ${state.settings.weekStartsMonday ? 'checked' : ''}></label><p class="form-error" data-form-error role="alert" hidden></p><button type="submit" class="button">設定を保存</button></form><div class="install-block"><h3>ホーム画面に追加</h3><p>iPhone・iPadはSafariの共有メニューから「ホーム画面に追加」。PCはブラウザのインストール機能をご利用ください。</p><button class="button small" id="install-app">インストール方法</button><p id="offline-status" class="field-hint">オフラインの準備を確認中…</p></div></section><section class="settings-card" id="backup-section"><div class="panel-heading"><h2>${icon('shield')} バックアップ・復元</h2></div><p class="backup-description">この端末の情報をJSONファイルに保存します。別の端末では、そのファイルから復元できます。</p><dl class="backup-meta"><div><dt>保存方式</dt><dd>${e(storageKind)} · 端末内</dd></div><div><dt>登録済み</dt><dd>情報 ${state.items.length}件 / メンバー ${state.members.length}名 / 予約 ${state.reservations.length}件</dd></div><div><dt>前回の書き出し</dt><dd>${state.settings.lastBackupAt ? e(new Date(state.settings.lastBackupAt).toLocaleString('ja-JP')) : 'まだ書き出していません'}</dd></div></dl><div class="backup-buttons"><button class="button primary" id="export-backup">${icon('download')}バックアップ書き出し</button><label class="button restore-button">${icon('upload')}バックアップから復元<input id="restore-file" type="file" accept=".json,application/json" aria-label="バックアップファイルを選択"></label></div><p class="field-hint">復元前に件数を確認できます。復元は現在のデータを置き換えます。</p><p class="info-note">端末間の自動同期はありません。ブラウザのデータ削除に備えて、定期的にバックアップしてください。</p></section></div><section class="integration-note">${icon('link')}<div><h3>Microsoft連携について</h3><p>現在は未接続です。Teams・Outlook・OneDriveの権限がなくても、すべての手動管理機能を使えます。</p></div></section>`;
}
