import { GROUPS, dateKey, shortDate } from '../domain/model.js';
import { calendarEvents } from '../integrations/outlook.js';
import { escapeHtml as e, icon, empty } from './helpers.js';
import { itemRow } from './manage.js';
export function schedulePage(state, ui) {
  const month = new Date(ui.calendarYear, ui.calendarMonth, 1);
  const events = calendarEvents(state.items, ui.externalEvents || []);
  const offset = (month.getDay() + (state.settings.weekStartsMonday ? 6 : 0)) % 7;
  const dayCount = new Date(ui.calendarYear, ui.calendarMonth + 1, 0).getDate();
  const cells = Math.ceil((offset + dayCount) / 7) * 7;
  const days = Array.from({ length: cells }, (_, index) => {
    const date = new Date(ui.calendarYear, ui.calendarMonth, index - offset + 1);
    const key = dateKey(date), dayEvents = events.filter(event => event.date === key);
    return `<button class="calendar-day ${date.getMonth() !== ui.calendarMonth ? 'outside-month' : ''} ${key === dateKey() ? 'is-today' : ''} ${key === ui.selectedDate ? 'selected' : ''}" data-calendar-date="${key}" aria-label="${e(key)}、${dayEvents.length}件の予定" ${key === ui.selectedDate ? 'aria-pressed="true"' : 'aria-pressed="false"'}><span class="day-number">${date.getDate()}</span><span class="calendar-event-lines">${dayEvents.slice(0, 2).map(event => `<span class="calendar-event ${e(event.type)}">${e(event.title)}</span>`).join('')}${dayEvents.length > 2 ? `<span class="event-more">ほか${dayEvents.length - 2}件</span>` : ''}</span>${dayEvents.length ? `<span class="event-dots" aria-hidden="true">${dayEvents.slice(0, 3).map(event => `<i class="${e(event.type)}"></i>`).join('')}</span>` : ''}</button>`;
  }).join('');
  const weekdays = state.settings.weekStartsMonday ? ['月', '火', '水', '木', '金', '土', '日'] : ['日', '月', '火', '水', '木', '金', '土'];
  const agenda = events.filter(event => event.date === ui.selectedDate).sort((a, b) => a.startsAt - b.startsAt);
  return `<div class="page-heading"><div><p class="eyebrow">MY SCHEDULE</p><h1>予定</h1><p class="page-description">自分の期限と、メンバーの予定を確認。</p></div><button class="button primary" data-new-item="task" data-default-date="${e(ui.selectedDate)}">${icon('plus')}新規登録</button></div><div id="alerts"></div><section class="calendar-card"><div class="calendar-toolbar"><h2>${icon('calendar')} 自分の予定</h2><div class="calendar-controls"><button class="icon-button" data-month-step="-1" aria-label="前の月">${icon('chevronLeft')}</button><strong>${ui.calendarYear}年${ui.calendarMonth + 1}月</strong><button class="icon-button" data-month-step="1" aria-label="次の月">${icon('chevronRight')}</button><button class="button small" data-calendar-today>今日</button></div></div><div class="calendar-weekdays">${weekdays.map(day => `<span class="${day === '日' ? 'sunday' : day === '土' ? 'saturday' : ''}">${day}</span>`).join('')}</div><div class="calendar-grid">${days}</div><div class="calendar-legend"><span><i class="task"></i>期限付き作業</span><span><i class="memo"></i>メモ</span><span><i class="review"></i>あとで確認</span><small>完了した作業は表示されません</small></div></section><section class="list-section agenda"><header class="section-heading"><h2>${e(shortDate(ui.selectedDate))}の予定 <span class="count-badge">${agenda.length}</span></h2><span class="section-note">${e(ui.selectedDate)}</span></header>${agenda.length ? agenda.map(event => event.itemId ? itemRow(state.items.find(item => item.id === event.itemId)) : `<div class="item-row"><span class="item-title">【${e(shortDate(event.date))}】${e(event.title)}</span><span class="row-source">Outlook</span></div>`).join('') : empty('この日の予定はありません', '期限を設定した情報がカレンダーに表示されます')}</section>${membersPanel(state, ui)}`;
}
export function membersPanel(state, ui) {
  const members = state.members.filter(member => member.group === ui.memberGroup).sort((a, b) => a.name.localeCompare(b.name, 'ja'));
  return `<section class="members-panel"><div class="panel-heading"><h2>${icon('people')} 他メンバーの予定</h2><label class="date-picker">表示日<input type="date" id="member-date" value="${e(ui.memberDate)}" aria-label="メンバー予定の表示日"></label></div><div class="member-tabs" role="group" aria-label="メンバーグループ">${Object.entries(GROUPS).map(([group, { label }]) => `<button data-member-group="${group}" class="${group === ui.memberGroup ? 'selected' : ''}" aria-pressed="${group === ui.memberGroup}">${label}<span>${state.members.filter(m => m.group === group).length}</span></button>`).join('')}</div><div class="members-list">${members.length ? members.map(member => `<button class="member-row" data-member-detail="${e(member.id)}"><strong>${e(member.name)}</strong><span>：${e((member.schedules[ui.memberDate] || '').split(/\r?\n/).find(line => line.trim()) || '予定なし')}</span><small>詳細</small></button>`).join('') : empty('メンバーはまだ登録されていません', 'その他の「メンバー管理」から追加してください')}</div></section>`;
}
