import { jsonDeletionCandidates } from '../domain/json-cleanup.js';

import { escapeHtml as e, icon } from './helpers.js';

export function otherPage(state, ui, storageKind) {
  const candidates = jsonDeletionCandidates(state);
  const missingNames = candidates.filter(row => !row.fileName).length;
  return `<div class="page-heading"><div><p class="eyebrow">WORKSPACE TOOLS</p><h1>その他</h1><p class="page-description">設定、データの保管と元JSONの整理。</p></div></div><div id="alerts"></div>
    <nav class="section-jumps" aria-label="その他の項目"><a href="#cleanup-section" data-scroll="cleanup-section">元JSONの整理</a><a href="#settings-section" data-scroll="settings-section">設定</a><a href="#backup-section" data-scroll="backup-section">バックアップ・復元</a></nav>
    
    <section class="settings-card" id="cleanup-section"><div class="panel-heading"><div><h2>${icon('download')} 元JSONの整理</h2><p class="field-hint">Power Automateで利用するための削除候補をJSONに書き出します。</p></div><button class="button" id="export-json-cleanup">JSON削除対象を書き出す</button></div><div class="todo-result-summary"><span>削除候補：${candidates.length}件</span><span>手動削除：${candidates.filter(row => row.reason === 'manual-delete').length}件</span><span>完了後180日以上：${candidates.filter(row => row.reason === 'completed-over-180-days').length}件</span></div><p class="field-hint">アプリで手動削除した取込データは即時、完了した取込データは180日経過後に候補になります。未完了は含みません。業務データやOneDriveのファイルは自動削除しません。</p>${missingNames ? `<p class="info-note">${missingNames}件は旧版の取込元ファイル名が未保存です。元JSONを再度取り込むと、重複をスキップしながらファイル名だけを補完します。補完前の書き出しではfileNameがnullになります。</p>` : ''}</section>
    <div class="other-grid"><section class="settings-card" id="settings-section"><div class="panel-heading"><h2>${icon('settings')} 設定</h2></div><form id="settings-form"><label class="setting-row"><span>期限時刻の初期値<small>新規登録時に使用</small></span><input name="defaultDueTime" type="time" required value="${e(state.settings.defaultDueTime)}"></label><label class="setting-row"><span>アプリ内アラーム<small>アプリを開いたときに確認</small></span><input type="checkbox" name="alarmsEnabled" ${state.settings.alarmsEnabled ? 'checked' : ''} aria-label="アプリ内アラームを有効にする"></label><label class="setting-row"><span>カレンダーは月曜始まり</span><input name="weekStartsMonday" type="checkbox" ${state.settings.weekStartsMonday ? 'checked' : ''}></label><p class="form-error" data-form-error role="alert" hidden></p><button type="submit" class="button">設定を保存</button></form><div class="install-block"><h3>ホーム画面に追加</h3><p>iPhone・iPadはSafariの共有メニューから「ホーム画面に追加」。PCはブラウザのインストール機能をご利用ください。</p><button class="button small" id="install-app">インストール方法</button><p id="offline-status" class="field-hint">オフラインの準備を確認中…</p></div></section>
    <section class="settings-card" id="backup-section"><div class="panel-heading"><h2>${icon('shield')} バックアップ・復元</h2></div><p class="backup-description">この端末の情報をJSONファイルに保存します。別の端末では、そのファイルから復元できます。</p><dl class="backup-meta"><div><dt>保存方式</dt><dd>${e(storageKind)} · 端末内</dd></div><div><dt>登録済み</dt><dd>情報 ${state.items.length}件 / 予約 ${state.reservations.length}件 / 削除対象履歴 ${state.jsonDeletionHistory.length}件</dd></div><div><dt>前回の書き出し</dt><dd>${state.settings.lastBackupAt ? e(new Date(state.settings.lastBackupAt).toLocaleString('ja-JP')) : 'まだ書き出していません'}</dd></div></dl><div class="backup-buttons"><button class="button primary" id="export-backup">${icon('download')}バックアップ書き出し</button><label class="button restore-button">${icon('upload')}バックアップから復元<input id="restore-file" type="file" accept=".json,application/json" aria-label="バックアップファイルを選択"></label></div><p class="field-hint">復元前に件数を確認できます。復元は現在のデータを置き換えます。取込フォルダー名と日時の解釈は保持しますが、フォルダーの読取権限は復元しません。復元後に再設定してください。</p><p class="info-note">端末間の自動同期はありません。ブラウザのデータ削除に備えて、定期的にバックアップしてください。</p></section></div>
    <section class="integration-note">${icon('link')}<div><h3>Microsoft連携について</h3><p>現在は未接続です。Teams・Outlook・OneDriveの権限がなくても、すべての手動管理機能を使えます。</p></div></section>`;
}
