import { escapeHtml as e, icon } from './helpers.js';
import { showDialog, errorArea } from './dialog.js';

export function reservationExportToolbar({ supported = false, name = '', busy = false, warning = '' } = {}) {
  return `<div class="reservation-export-tools"><div><button class="button small" data-reservation-folder-settings ${busy ? 'disabled' : ''}>${icon('settings')}保存フォルダー設定</button><button class="button small" data-export-reservations ${busy ? 'disabled' : ''}>${icon('download')}${busy ? '書き出し中…' : '予約JSONを書き出す'}</button></div><p class="field-hint">${supported ? `保存先：${name ? e(name) : '未設定'}。全予約と取消履歴を書き出します。登録・編集・削除後は再度押してください。` : 'このブラウザではJSONをダウンロードして、OneDriveの「MY仕事管理 / Teams送信予約」に保存できます。フォルダーへ直接保存する場合はWindows Edge / Chromeを使用してください。'}${warning ? `<br>${e(warning)}` : ''}</p></div>`;
}
export function reservationDownloadDialog(entries) {
  return showDialog('予約JSONを書き出す', `<p>このブラウザではフォルダーへの直接保存に対応していません。1件ずつダウンロードし、OneDriveの <strong>MY仕事管理 / Teams送信予約</strong> に保存してください。</p><p class="field-hint">編集後は同じ予約ID.jsonを置き換えてください。取消済みのJSONも出力できます。</p>${entries.length ? entries.map(({ id, reservation, deletedAt }) => `<div class="notification-row"><div><strong>${e(reservation.groupName)}</strong><p>${e(reservation.scheduledAt.replace('T', ' '))}${deletedAt ? ' · 取消済み' : ''}</p></div><button class="button small" data-download-reservation="${e(id)}">この予約のJSONを書き出す</button></div>`).join('') : '<p>書き出す予約はありません。</p>'}<div class="dialog-actions"><button class="button" data-cancel>閉じる</button></div>`);
}
export function reservationExportSettings(folder) {
  return showDialog('予約JSONの保存フォルダー設定', `<p>Windows Edge / Chromeで、OneDrive同期フォルダー内の<br><strong>MY仕事管理 / Teams送信予約</strong>を選択してください。</p><p class="field-hint">フォルダーがない場合は先に作成してください。選択したフォルダー直下へ「予約ID.json」を保存します。To Do取込用のフォルダーとは別の設定です。</p><p>現在の保存先：<strong>${e(folder.handle?.name || '未設定')}</strong></p><p class="info-note">書き出しはボタン操作で実行します。OneDriveクラウドへの直接接続はありません。クラウドへの反映はWindowsのOneDrive同期が行います。ブラウザが再許可を求める場合があります。</p>${folder.warning ? `<p class="field-hint">${e(folder.warning)}</p>` : ''}${errorArea}<div class="dialog-actions"><button class="button" data-cancel>閉じる</button>${folder.supported ? `<button class="button primary" data-reservation-folder-choose>保存フォルダーを選択</button>` : '<span class="field-hint">フォルダー保存に対応していません。詳細からJSONをダウンロードしてください。</span>'}</div>`);
}
export function reservationExportResult(report) {
  return showDialog('予約JSONの書き出し結果', `<div class="todo-result-summary" role="status"><strong>書き出し完了</strong><span>保存：${report.written}件（取消：${report.cancelled}件）</span><span>エラー：${report.error}件</span></div><p class="field-hint">これは同期フォルダーへの保存結果です。OneDriveへの同期完了はWindows側で確認してください。Teamsへの送信は行っていません。</p>${report.results.length ? `<details class="todo-result-details" ${report.error ? 'open' : ''}><summary>ファイル別の結果</summary>${report.results.map(r => `<div><strong>${e(r.fileName)}</strong><span>${r.ok ? '保存済み' : e(r.message)}</span></div>`).join('')}</details>` : '<p>書き出す予約はありません。</p>'}<div class="dialog-actions"><button class="button" data-reservation-folder-settings>保存フォルダー設定</button><button class="button primary" data-cancel>閉じる</button></div>`, { wide: true });
}
