import { id, dateKey, localDateTime, safeLink } from '../domain/model.js';
import { escapeHtml as e, icon, empty, dateTimeLabel } from './helpers.js';
import { showDialog, errorArea } from './dialog.js';
import { reservationExportToolbar } from './reservation-export.js';
export function reservationsPanel(state, status, exportState = {}) {
  const reservations = state.reservations.filter(r => status === 'all' || r.status === status).sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt));
  return `<section class="settings-card reservation-card" id="reservation-section"><div class="panel-heading"><div><h2>${icon('send')} Teams送信予約</h2><p class="field-hint">本文を準備して、予定日時にTeamsで手動送信。</p></div><button class="button primary small" data-new-reservation>${icon('plus')}予約を追加</button></div><div class="reservation-toolbar"><span class="manual-badge">手動送信</span><select id="reservation-filter" aria-label="送信予約の状態で絞り込み">${[['pending', '未送信'], ['sent', '送信済み'], ['all', 'すべて']].map(([value, label]) => `<option value="${value}" ${status === value ? 'selected' : ''}>${label}</option>`).join('')}</select></div>${reservationExportToolbar(exportState)}${reservations.length ? reservations.map(r => {
    const due = r.status === 'pending' && new Date(r.scheduledAt).getTime() <= Date.now();
    return `<div class="reservation-row ${due ? 'due' : ''}"><div><span class="reservation-date">${e(dateTimeLabel(r.scheduledAt))}</span><strong>${e(r.groupName)}</strong><p>${e(r.body.split(/\r?\n/)[0])}</p></div><span class="status-badge ${due ? 'due' : ''} ${r.status}">${r.status === 'sent' ? '送信済み' : due ? '送信予定あり' : '未送信'}</span><button class="detail-link" data-reservation-detail="${e(r.id)}">詳細</button></div>`;
  }).join('') : empty(status === 'sent' ? '送信済みの予約はありません' : '送信予約はまだありません', '先の日付の送信も準備しておけます')}</section>`;
}
export function reservationDetail(r, exportState = {}) {
  const due = r.status === 'pending' && new Date(r.scheduledAt).getTime() <= Date.now();
  const link = safeLink(r.teamsLink);
  return showDialog('Teams送信予約の詳細', `<div class="detail-header"><span class="type-tag ${r.status === 'sent' ? 'done' : ''}">${r.status === 'sent' ? '送信済み' : due ? '送信予定があります' : '未送信'}</span><h3 class="detail-title">${e(r.groupName)}</h3></div><dl class="detail-meta"><div><dt>送信予定</dt><dd>${e(r.scheduledAt.replace('T', '　'))}</dd></div>${r.sentAt ? `<div><dt>送信済み日時</dt><dd>${e(new Date(r.sentAt).toLocaleString('ja-JP'))}</dd></div>` : ''}</dl><section class="detail-section"><h3>送信本文</h3><div class="body-text">${e(r.body)}</div></section><div class="send-tools"><button class="button" data-export-reservation="${e(r.id)}">この予約のJSONを書き出す</button><button class="button" data-download-reservation="${e(r.id)}">JSONをダウンロード</button><button class="button" data-copy-reservation="${e(r.id)}">本文をコピー</button>${link ? `<a href="${e(link)}" class="button" target="_blank" rel="noopener noreferrer">${icon('link')}Teamsで開く</a>` : ''}</div><p class="field-hint">実際にTeamsで送信してから「送信済みにする」を押してください。</p><div class="dialog-actions"><button class="button danger" data-delete-reservation="${e(r.id)}">削除</button><div><button class="button" data-edit-reservation="${e(r.id)}">編集</button><button class="button primary" data-reservation-sent="${e(r.id)}" data-sent="${r.status !== 'sent'}">${r.status === 'sent' ? '未送信に戻す' : '送信済みにする'}</button></div></div>`);
}
export function reservationForm(existing) {
  const now = new Date(); now.setHours(now.getHours() + 1, 0, 0, 0);
  const r = existing || { groupName: '', scheduledAt: localDateTime(now), body: '', teamsLink: '', status: 'pending' };
  const dialog = showDialog(existing ? '送信予約を編集' : '送信予約を追加', `<form id="reservation-form"><div class="form-grid"><label class="span-2">送信先グループ名 <span class="required">必須</span><input name="groupName" required maxlength="200" value="${e(r.groupName)}" placeholder="例：SV部 連絡用グループ"></label><label class="span-2">送信予定日時（日本時間） <span class="required">必須</span><input name="scheduledAt" type="datetime-local" required value="${e(r.scheduledAt)}"></label><label class="span-2">送信本文 <span class="required">必須</span><textarea name="body" required maxlength="50000" rows="7" placeholder="Teamsに送信したい本文">${e(r.body)}</textarea></label><label class="span-2">Teamsグループチャットのリンク（任意）<input name="teamsLink" type="url" maxlength="4000" value="${e(r.teamsLink)}" placeholder="https://teams.microsoft.com/…"></label><label>状態<select name="status"><option value="pending" ${r.status === 'pending' ? 'selected' : ''}>未送信</option><option value="sent" ${r.status === 'sent' ? 'selected' : ''}>送信済み</option></select></label></div><p class="info-note">自動送信は行いません。予定時刻になるとアプリ内でお知らせします。保存後、一覧または詳細の書き出しボタンで予約JSONを保存できます。</p>${errorArea}<div class="dialog-actions"><button type="button" class="button" data-cancel>キャンセル</button><button type="submit" class="button primary">保存する</button></div></form>`, { form: true });
  const form = dialog.querySelector('form');
  return { form, read() { const data = new FormData(form), now = new Date().toISOString(), status = data.get('status'); return { ...(existing || { id: id(), extensions: {}, createdAt: now }), groupName: data.get('groupName').trim(), scheduledAt: data.get('scheduledAt'), body: data.get('body'), teamsLink: data.get('teamsLink').trim(), status, sentAt: status === 'sent' ? existing?.sentAt || now : null, updatedAt: now }; } };
}
